name: ImageOnMap
api: 5.0.0
version: 1.1.1
main: czechpmdevs\imageonmap\ImageOnMap
description: PocketMine plugin which allows to add images to map items
author: CzechPMDevs
authors: [VixikHD]

permissions:
  imageonmap.command:
    default: op
    description: Permission for all the ImageOnMap commands