name: ImageOnMap
api: 4.0.0
version: 1.0.4
main: czechpmdevs\imageonmap\ImageOnMap
description: PocketMine plugin which allows to add images to map items
author: CzechPMDevs
authors: [VixikHD]

permissions:
  imageonmap.command:
    default: op
    description: Permission for all the ImageOnMap commands